# Generated by Django 3.2.6 on 2021-11-29 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=20)),
                ('surname', models.TextField(max_length=40)),
                ('phone_number', models.IntegerField()),
                ('date_of_birth', models.DateField()),
                ('education', models.TextField(max_length=1000)),
                ('professional_skills', models.TextField(max_length=1000)),
                ('personal_qualities', models.TextField(max_length=1000)),
                ('additional_information', models.TextField(max_length=1000)),
                ('language', models.CharField(choices=[('RU', 'RUSSIAN'), ('ENG', 'ENGLISH')], max_length=3)),
            ],
        ),
    ]
