# Generated by Django 3.2.6 on 2021-12-06 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rezume', '0002_auto_20211201_1813'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='image',
            field=models.ImageField(default=1, upload_to='images'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='info',
            name='language',
            field=models.CharField(choices=[('RU', 'RUSSIAN'), ('ENG', 'ENGLISH')], max_length=3),
        ),
    ]
